config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  resources :pratos
  resources :qualificacoes
  resources :clientes
  root to: redirect("/inicio")

  resources :comentarios
  resources :restaurantes
  
  
  get "/inicio" => "restaurantes#index", as: :start
  get "restaurantes/:nome" => "restaurantes#show"

  

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
	has_many :qualificacoes
	has_and_belongs_to_many :pratos
	has_many :comentarios, as: :comentavel


	validates_uniqueness_of :nome
	validates_presence_of :nome, :especialidade
	validates_size_of :especialidade, maximum: 40
	validate :primeira_letra_deve_ser_maiuscula 

	def valor_total_gasto 
		self.qualificacoes.sum(:valor_gasto) 
	end

	private
	def primeira_letra_deve_ser_maiuscula
		errors.add("nome", "primeira letra deve ser maiuscula") unless nome =~ /[A-Z].*/
	end

end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
	def index 
		@restaurantes = Restaurante.order :nome

		respond_to do |format| 
			format.html {render "index"} 
			format.json {render json: @restaurantes} 
			format.xml { render xml: @restaurantes}
		end

	end

	def show
		@restaurante = Restaurante.find(params[:id])
	end

	def destroy
		restaurante = Restaurante.find(params[:id])
		restaurante.destroy
		redirect_to action: 'index'
	end

	def new
		 @restaurante = Restaurante.new 
	end

	def create
		@restaurante = Restaurante.new restaurante_params
		if @restaurante.save
			redirect_to(action: "show", id: @restaurante)
		else 
			render action: "new"
		end
	end

	def restaurante_params
		params.require(:restaurante).permit(:nome, :endereco, :especialidade)
	end

	def edit 
		@restaurante = Restaurante.find(params[:id]) 
	end

	def update 
		@restaurante = Restaurante.find(params[:id])
		if @restaurante.update_attributes restaurante_params
			redirect_to(action: "show", id: @restaurante)
		else
			render action: "edit"
		end
	end




end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.erb
<%= form_for @restaurante, :html => { :class => "form-horizontal restaurante" } do |f| %>

  <% if @restaurante.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @restaurante.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :endereco, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :endereco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:endereco) %>
  </div>
  <div class="form-group">
    <%= f.label :especialidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :especialidade, :class => 'form-control' %>
    </div>
    <%=f.error_span(:especialidade) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                restaurantes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/restaurantes/edit.html.erb
<%- model_class = Restaurante -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurantes/index.html.erb
<%- model_class = Restaurante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
      <th><%= model_class.human_attribute_name(:especialidade) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= link_to restaurante.id, restaurante_path(restaurante) %></td>
        <td><%= restaurante.nome %></td>
        <td><%= restaurante.endereco %></td>
        <td><%= restaurante.especialidade %></td>
        <td><%=l restaurante.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_restaurante_path(restaurante), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      restaurante_path(restaurante),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_restaurante_path,
            :class => 'btn btn-primary' %>

app/views/restaurantes/new.html.erb
<%- model_class = Restaurante -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurantes/show.html.erb
<%- model_class = Restaurante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @restaurante.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @restaurante.endereco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:especialidade) %>:</strong></dt>
  <dd><%= @restaurante.especialidade %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              restaurantes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_restaurante_path(@restaurante), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              restaurante_path(@restaurante),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<h3>Comentários</h3> 
<div id="comentarios"> 
    <%= render @restaurante.comentarios %> 
</div>
<%= novo_comentario @restaurante %>


<h3>Qualificação</h3> 
<div id="qualificacoes"> 
    <%= render @restaurante.qualificacoes %> 
</div>
<%= novo_qualificacao @restaurante %> 