config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  resources :pratos
  resources :qualificacoes
  resources :clientes
  root to: redirect("/inicio")

  resources :comentarios
  resources :restaurantes
  
  
  get "/inicio" => "restaurantes#index", as: :start
  get "restaurantes/:nome" => "restaurantes#show"

  

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :comentavel, polymorphic: true
	belongs_to :usuario
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)
    @comentario.usuario = current_usuario
    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
      format.js { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:conteudo, :author, :comentavel_type, :comentavel_id)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<p id='<%= "comentario_#{comentario.id}" %>'>
	<%= comentario.conteudo %>
	<%= comentario.usuario.email rescue nil %>

	<% if current_usuario = comentario.usuario.id rescue nil %>
	<%= link_to '(remover)', comentario, method: 'delete', remote: true, id: "remove_comentario_#{comentario.id}" %>
	<% end %>
</p>

<% content_for :js do %> 
  $('#remove_comentario_<%= comentario.id %>')
   .bind('ajax:success', function(){ 
    $('#comentario_<%= comentario.id %>').fadeOut();
   }); 
<% end %>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conteudo %><br>
    <%= f.text_field :conteudo %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/_novo_comentario.html.erb
<%= form_for Comentario.new, remote: true do |f| %> 
	<%= f.hidden_field :comentavel_id, value: comentavel.id %> 
	<%= f.hidden_field :comentavel_type, value: comentavel.class %> 
	<%= f.label :conteudo %> <br /> 
	<%= f.text_area :conteudo %>
	<% if current_usuario %>
    	<%= f.submit %> 
    <% end %>
<% end %>


<% content_for :js do %> 
	$('#new_comentarios').bind('ajax:complete', function(xhr, result){ 
		$('#comentarios').html(result.responseText); 
		$('textarea').val(""); 
	}); 
<% end %>

app/views/comentarios/create.js.erb
<%= render @comentario.comentavel.comentarios %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Conteudo</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.author %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comentario.author %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>