config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  resources :pratos
  resources :qualificacoes
  resources :clientes
  root to: redirect("/inicio")

  resources :comentarios
  resources :restaurantes
  
  
  get "/inicio" => "restaurantes#index", as: :start
  get "restaurantes/:nome" => "restaurantes#show"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Food" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

   <%= nav_bar static: :top, brand: "VotaFood" do %> 
   <%= menu_group do %> 
     <%= menu_item "Home", root_path %> 
     <%= menu_item "Restaurantes", restaurantes_path %> 
     <%= menu_item "Clientes", clientes_path %> 
     <%= menu_item "Qualificações", qualificacoes_path %> 
     <%= menu_item "Pratos", pratos_path %> 
   <% end %> 
   <% if current_usuario %> 
    <%= menu_group pull: :right do %> 
        <%= menu_item "Log Out", destroy_usuario_session_path, :method => :delete %> 
      <% end %>
      <% else %> 
        <%= menu_group pull: :right do %>
        <%= menu_item "Cadastre-se", new_usuario_registration_path %> 
        <%= menu_item "Login", new_usuario_session_path %> 
      <% end %> 
    <% end %>
   <% end %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

   <script type="text/javascript">
    <%= yield :js %>
   </script>

  </body>
</html>

app/views/layouts/application.js.erb
<%= yield %> 

<script> 
	<%= yield :js %>
 </script>